version: '3.0'
services:
  postgres:
    image: postgres
    restart: always
    container_name: dbhackathon
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: hackathon
      POSTGRES_USER: hackathon
      POSTGRES_PASSWORD: hackathon
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  postgres:
