# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    env:
      BUSINESS_SECRET: business
      USER_SECRET: user
      DATABASE_URL: "postgresql://hackathon:hackathon@194.67.116.26:5433/hackathon"  

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: (cd ./back-end && npm install)
    - run: (cd ./back-end && npm run build --if-present)
    - run: (cd ./back-end && npm run generate --if-present)
    - run: pm2 restart DeployApp
